### PR TITLE
Basic Fixes for i18n locales

### LINKED ISSUE #110: Reenable basic support for i18n locales in docs portal
Most chinese (and probably other locales) static pages are currently rendering this (React?) error:

"Cannot destructure property 'versions' of 'n' as it is undefined."

AC:
- Static pages should render the English content by default.
- Overridden pages in `i18n/...` should render the appropriate locale version.

This ticket is High Priority - related to https://github.com/eosnetworkfoundation/devrel/issues/213

### PR DESCRIPTION
**Pull request by ericpassmore**
Fixes #110 
Gets the pages up and running again for non-en locals. 

To test follow software installation instructions 
https://github.com/eosnetworkfoundation/docsgen/blob/main/docs/FirstInstallSoftware.md
Then run these commands, this will take a while. 
```
mkdir -p ~/eosnetworkfoundation/build_root
./clean_rebuild.sh -d ~/eosnetworkfoundation/build_root
cd ~/eosnetworkfoundation/build_root/devdocs
npm run serve
```
Starts a server on localhost:3000. Browse around. Try adding a 'zh' or 'ko' to the front of the url. Example
http://localhost:3000/docs/latest/smart-contracts/tutorials/understanding-ABI-files
http://localhost:3000/zh/docs/latest/smart-contracts/tutorials/understanding-ABI-files

### CODE REVIEW

File: web/docusaurus/src/components/CustomTOC/CustomTOC.tsx [hunk 1]
```diff
@@ -86,10 +102,18 @@ export default function CustomTOC({ doc, onClick }) {
...
 
   const handleOnChange = (selectedOption) => {
+    // grab main docusarus configuration
+    const {siteConfig} = useDocusaurusContext();
     const { path } = selectedOption;
-    const { pluginId, version } = getPathKey(pathname);
-    const newPath = pathname.replace(`/${pluginId}/${version}`, path);
-    
+    const { localKey, pluginId, version } = getPathKey(pathname);
+    let newPath = undefined;
```
Comment (AlexGriffith10) [inline web/docusaurus/src/components/CustomTOC/CustomTOC.tsx:109]: not worth changing if you don't feel like it but I believe this defaults to undefined so you can just have 
```let newPath```

File: web/docusaurus/src/theme/TOC/index.js [hunk 2]
```diff
@@ -88,9 +104,14 @@ export default function TOC({className, ...props}) {
 
   const handleOnChange = (selectedOption) => {
     const { path } = selectedOption;
-    const { pluginId, version } = getPathKey(pathname);
-    const newPath = pathname.replace(`/${pluginId}/${version}`, path);
-    
+    const { localKey, pluginId, version } = getPathKey(pathname);
+    let newPath = undefined;
```
Comment (AlexGriffith10) [inline web/docusaurus/src/theme/TOC/index.js:108]: same as above pretty sure you just need ```let newPath```

**Review by AlexGriffith10 — APPROVED** [review]

**Review by lparisc — APPROVED** [review]
Repro'd fix successfully.
